apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-exclustion
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amonsum-stack/test-exclustion
    targetRevision: main
    path: .
    directory:
      recurse: false
      exclude: '{catalog-info.yaml,argocd-app.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false