apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-without-probes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amonsum-stack/testing-without-probes
    targetRevision: main
    path: .
    directory:
      exclude: 'catalog-info.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false